// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM2oWUx5EY6D7n741xI_svK9Rkqw79Pjs',
    appId: '1:3311634229:web:572572773d5d4e80622e7c',
    messagingSenderId: '3311634229',
    projectId: 'basic-project-lab-40419',
    authDomain: 'basic-project-lab-40419.firebaseapp.com',
    storageBucket: 'basic-project-lab-40419.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmAuHzQ8DnAiqifvUygkoG1fz4i5bvpvY',
    appId: '1:3311634229:android:963e6805cb30c413622e7c',
    messagingSenderId: '3311634229',
    projectId: 'basic-project-lab-40419',
    storageBucket: 'basic-project-lab-40419.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0iriGQEddAUbzEKEkHLHdrSAINEes9LU',
    appId: '1:3311634229:ios:7fc57cb8a23c8679622e7c',
    messagingSenderId: '3311634229',
    projectId: 'basic-project-lab-40419',
    storageBucket: 'basic-project-lab-40419.appspot.com',
    iosBundleId: 'cnu.basicprojectlab.basicProjectLab',
  );
}
